### ISSUE TITLE
Multiple TemporaryVariable to one card not working

### ISSUE THREAD

**Issue by jf84398942813** [spkesDE/TemporaryVariables#1]
Hi,
I'm faced to an issue in particular case.
In AdvancedFlow, I have many notification at the end. When I use multiple TempVariable to the same notification card, I get an error.
Below, the flow to illustrate what is working with Homey built-in variable (Logiq) and with your solution (Temporary Variable) :
![2022-09-07_090129](https://user-images.githubusercontent.com/82017111/188811849-33660b47-de50-4fca-869e-e0dcbf841d82.jpg)

You solution is preferred in this case, but not work as expected.
Let me know if you need more information.

Best regards.

**Comment by spkesDE** [comment]
Hello @jf84398942813,
this is a issue because of the flows since the flow runs asynchrone. You have to add a all card to the flow.
![image](https://user-images.githubusercontent.com/1682314/188813021-98358385-2b30-4824-b5ef-c15417d34fe6.png)

Edit: Since you have 3 different triggers, you have to have 3 different send message card, since it will not always be the case that all the triggers has been run at the same time.

**Comment by jf84398942813** [comment]
The ALL is like a AND logic operator, so in my case it's a OR I need and so it's a ANY card, but same behavior. ALL or ANY card does not work :
![2022-09-07_092259](https://user-images.githubusercontent.com/82017111/188815751-5f7c1031-3466-4287-b599-88f36581001a.jpg)
![2022-09-07_092346](https://user-images.githubusercontent.com/82017111/188815766-1df7dad4-ad4b-452a-96df-324d961d20ab.jpg)

**Comment by spkesDE** [comment]
I know. You have "3 flows" what will Combine into one and your last card use all 3 flows. Since you use all 3 Tokens at the end  all 3 token has to be created at that point. I can't change that. You have to restructure your flow that all 3 token has been created.
The gray flow hasn't run, that's why 2 of the 3 token hasent been created and you got the error.

**Comment by jf84398942813** [comment]
ok understand.
it's good to know for the next.

thanks.
